/**
 * V3 Token 合约 ABI
 * 来源：Sepolia Etherscan 已验证合约 0x9C79BeaE0d9eBE8530A4F5B86c8445c62F234c89
 * 构造参数：(usdt_, name_, symbol_, limitGate_, redeemQueue_, investmentVault_)
 */
export const TOKEN_ABI = [
	{
		inputs: [
			{ internalType: "address", name: "usdt_", type: "address" },
			{ internalType: "string", name: "name_", type: "string" },
			{ internalType: "string", name: "symbol_", type: "string" },
			{ internalType: "address", name: "limitGate_", type: "address" },
			{ internalType: "address", name: "redeemQueue_", type: "address" },
			{ internalType: "address", name: "investmentVault_", type: "address" },
		],
		stateMutability: "nonpayable",
		type: "constructor",
	},
	{ inputs: [], name: "ArrayLengthMismatch", type: "error" },
	{
		inputs: [{ internalType: "uint256", name: "length", type: "uint256" }],
		name: "ArrayTooLarge",
		type: "error",
	},
	{ inputs: [], name: "AuthorizationAlreadyUsed", type: "error" },
	{ inputs: [], name: "AuthorizationExpired", type: "error" },
	{ inputs: [], name: "AuthorizationInvalid", type: "error" },
	{ inputs: [], name: "AuthorizationNotYetValid", type: "error" },
	{ inputs: [], name: "AuthorizationWindowTooLong", type: "error" },
	{ inputs: [], name: "ECDSAInvalidSignature", type: "error" },
	{
		inputs: [{ internalType: "uint256", name: "length", type: "uint256" }],
		name: "ECDSAInvalidSignatureLength",
		type: "error",
	},
	{
		inputs: [{ internalType: "bytes32", name: "s", type: "bytes32" }],
		name: "ECDSAInvalidSignatureS",
		type: "error",
	},
	{
		inputs: [
			{ internalType: "address", name: "spender", type: "address" },
			{ internalType: "uint256", name: "allowance", type: "uint256" },
			{ internalType: "uint256", name: "needed", type: "uint256" },
		],
		name: "ERC20InsufficientAllowance",
		type: "error",
	},
	{
		inputs: [
			{ internalType: "address", name: "sender", type: "address" },
			{ internalType: "uint256", name: "balance", type: "uint256" },
			{ internalType: "uint256", name: "needed", type: "uint256" },
		],
		name: "ERC20InsufficientBalance",
		type: "error",
	},
	{
		inputs: [{ internalType: "address", name: "approver", type: "address" }],
		name: "ERC20InvalidApprover",
		type: "error",
	},
	{
		inputs: [{ internalType: "address", name: "receiver", type: "address" }],
		name: "ERC20InvalidReceiver",
		type: "error",
	},
	{
		inputs: [{ internalType: "address", name: "sender", type: "address" }],
		name: "ERC20InvalidSender",
		type: "error",
	},
	{
		inputs: [{ internalType: "address", name: "spender", type: "address" }],
		name: "ERC20InvalidSpender",
		type: "error",
	},
	{ inputs: [], name: "InvalidBatchLength", type: "error" },
	{ inputs: [], name: "InvalidShortString", type: "error" },
	{
		inputs: [
			{ internalType: "address", name: "user", type: "address" },
			{ internalType: "uint256", name: "amount", type: "uint256" },
		],
		name: "RedeemLimitExceeded",
		type: "error",
	},
	{ inputs: [], name: "ReentrancyGuardReentrantCall", type: "error" },
	{
		inputs: [{ internalType: "address", name: "token", type: "address" }],
		name: "SafeERC20FailedOperation",
		type: "error",
	},
	{
		inputs: [{ internalType: "string", name: "str", type: "string" }],
		name: "StringTooLong",
		type: "error",
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: "address", name: "currentAdmin", type: "address" },
			{ indexed: true, internalType: "address", name: "pendingAdmin", type: "address" },
		],
		name: "AdminTransferProposed",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: "address", name: "previousAdmin", type: "address" },
			{ indexed: true, internalType: "address", name: "newAdmin", type: "address" },
		],
		name: "AdminTransferred",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: "address", name: "owner", type: "address" },
			{ indexed: true, internalType: "address", name: "spender", type: "address" },
			{ indexed: false, internalType: "uint256", name: "value", type: "uint256" },
		],
		name: "Approval",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: "address", name: "authorizer", type: "address" },
			{ indexed: true, internalType: "bytes32", name: "nonce", type: "bytes32" },
		],
		name: "AuthorizationCanceled",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: "address", name: "authorizer", type: "address" },
			{ indexed: true, internalType: "bytes32", name: "nonce", type: "bytes32" },
		],
		name: "AuthorizationUsed",
		type: "event",
	},
	{ anonymous: false, inputs: [], name: "EIP712DomainChanged", type: "event" },
	{ anonymous: false, inputs: [], name: "InvestmentVaultCancelled", type: "event" },
	{
		anonymous: false,
		inputs: [{ indexed: true, internalType: "address", name: "vault", type: "address" }],
		name: "InvestmentVaultChanged",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: "address", name: "newVault", type: "address" },
			{ indexed: false, internalType: "uint256", name: "effectiveTime", type: "uint256" },
		],
		name: "InvestmentVaultProposed",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: "address", name: "account", type: "address" },
			{ indexed: false, internalType: "uint256", name: "usdtAmount", type: "uint256" },
		],
		name: "Minted",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [{ indexed: true, internalType: "address", name: "admin", type: "address" }],
		name: "Paused",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: "address", name: "account", type: "address" },
			{ indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
		],
		name: "Redeemed",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: "address", name: "from", type: "address" },
			{ indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
			{ indexed: false, internalType: "uint256", name: "bookkeepingReduction", type: "uint256" },
		],
		name: "ReserveReturned",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: "address", name: "vault", type: "address" },
			{ indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
		],
		name: "ReserveWithdrawn",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: "address", name: "to", type: "address" },
			{ indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
		],
		name: "SelfTokenRescued",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [{ indexed: false, internalType: "uint256", name: "amount", type: "uint256" }],
		name: "TaxAmountSet",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: "address", name: "account", type: "address" },
			{ indexed: false, internalType: "bool", name: "exempt", type: "bool" },
		],
		name: "TaxExemptSet",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [{ indexed: true, internalType: "address", name: "receiver", type: "address" }],
		name: "TaxReceiverSet",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: "address", name: "token", type: "address" },
			{ indexed: true, internalType: "address", name: "to", type: "address" },
			{ indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
		],
		name: "TokenRescued",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: "address", name: "from", type: "address" },
			{ indexed: true, internalType: "address", name: "to", type: "address" },
			{ indexed: false, internalType: "uint256", name: "value", type: "uint256" },
		],
		name: "Transfer",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [{ indexed: true, internalType: "address", name: "admin", type: "address" }],
		name: "Unpaused",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: "address", name: "to", type: "address" },
			{ indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
		],
		name: "UsdtRescued",
		type: "event",
	},
	{
		inputs: [],
		name: "BATCH_TRANSFER_WITH_AUTHORIZATION_TYPEHASH",
		outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "MAX_AUTH_WINDOW",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "MAX_BATCH_SIZE",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "TRANSFER_WITH_AUTHORIZATION_TYPEHASH",
		outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "USDT",
		outputs: [{ internalType: "contract IERC20", name: "", type: "address" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "VAULT_TIMELOCK",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{ inputs: [], name: "acceptAdmin", outputs: [], stateMutability: "nonpayable", type: "function" },
	{
		inputs: [],
		name: "acceptInvestmentVault",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [],
		name: "admin",
		outputs: [{ internalType: "address", name: "", type: "address" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "address", name: "owner", type: "address" },
			{ internalType: "address", name: "spender", type: "address" },
		],
		name: "allowance",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "address", name: "spender", type: "address" },
			{ internalType: "uint256", name: "value", type: "uint256" },
		],
		name: "approve",
		outputs: [{ internalType: "bool", name: "", type: "bool" }],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "address", name: "authorizer", type: "address" },
			{ internalType: "bytes32", name: "nonce", type: "bytes32" },
		],
		name: "authorizationState",
		outputs: [{ internalType: "bool", name: "", type: "bool" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "address", name: "account", type: "address" }],
		name: "balanceOf",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "address", name: "from", type: "address" },
			{ internalType: "address[]", name: "tos", type: "address[]" },
			{ internalType: "uint256[]", name: "amounts", type: "uint256[]" },
			{ internalType: "uint256", name: "validAfter", type: "uint256" },
			{ internalType: "uint256", name: "validBefore", type: "uint256" },
			{ internalType: "bytes32", name: "nonce", type: "bytes32" },
			{ internalType: "uint8", name: "v", type: "uint8" },
			{ internalType: "bytes32", name: "r", type: "bytes32" },
			{ internalType: "bytes32", name: "s", type: "bytes32" },
		],
		name: "batchTransferWithAuthorization",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "address", name: "authorizer", type: "address" },
			{ internalType: "bytes32", name: "nonce", type: "bytes32" },
		],
		name: "cancelAuthorization",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [],
		name: "cancelPendingInvestmentVault",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [],
		name: "decimals",
		outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
		stateMutability: "pure",
		type: "function",
	},
	{
		inputs: [],
		name: "eip712Domain",
		outputs: [
			{ internalType: "bytes1", name: "fields", type: "bytes1" },
			{ internalType: "string", name: "name", type: "string" },
			{ internalType: "string", name: "version", type: "string" },
			{ internalType: "uint256", name: "chainId", type: "uint256" },
			{ internalType: "address", name: "verifyingContract", type: "address" },
			{ internalType: "bytes32", name: "salt", type: "bytes32" },
			{ internalType: "uint256[]", name: "extensions", type: "uint256[]" },
		],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "investmentVault",
		outputs: [{ internalType: "address", name: "", type: "address" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "investmentVaultEffectiveTime",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "address", name: "account", type: "address" }],
		name: "isTaxExempt",
		outputs: [{ internalType: "bool", name: "", type: "bool" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "limitGate",
		outputs: [{ internalType: "contract ILimitGate", name: "", type: "address" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "usdtAmount", type: "uint256" }],
		name: "mint",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [],
		name: "name",
		outputs: [{ internalType: "string", name: "", type: "string" }],
		stateMutability: "view",
		type: "function",
	},
	{ inputs: [], name: "pause", outputs: [], stateMutability: "nonpayable", type: "function" },
	{
		inputs: [],
		name: "paused",
		outputs: [{ internalType: "bool", name: "", type: "bool" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "pendingAdmin",
		outputs: [{ internalType: "address", name: "", type: "address" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "pendingInvestmentVault",
		outputs: [{ internalType: "address", name: "", type: "address" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "address", name: "newVault", type: "address" }],
		name: "proposeInvestmentVault",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "amount", type: "uint256" }],
		name: "queueBurn",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "address", name: "to", type: "address" },
			{ internalType: "uint256", name: "amount", type: "uint256" },
		],
		name: "queuePayUsdt",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "address", name: "to", type: "address" },
			{ internalType: "uint256", name: "amount", type: "uint256" },
		],
		name: "queueTransfer",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "amount", type: "uint256" }],
		name: "redeem",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [],
		name: "redeemQueue",
		outputs: [{ internalType: "contract IRedeemQueue", name: "", type: "address" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "address", name: "to", type: "address" }],
		name: "rescueExcessToken",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "address", name: "to", type: "address" }],
		name: "rescueExcessUsdt",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "address", name: "to", type: "address" }],
		name: "rescueGateToken",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "address", name: "token", type: "address" },
			{ internalType: "address", name: "to", type: "address" },
		],
		name: "rescueOtherToken",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "address", name: "to", type: "address" }],
		name: "rescueSelfToken",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "amount", type: "uint256" }],
		name: "returnReserve",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "amount", type: "uint256" }],
		name: "setTaxAmount",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "address", name: "account", type: "address" },
			{ internalType: "bool", name: "exempt", type: "bool" },
		],
		name: "setTaxExempt",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "address", name: "receiver", type: "address" }],
		name: "setTaxReceiver",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [],
		name: "symbol",
		outputs: [{ internalType: "string", name: "", type: "string" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "taxAmount",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "taxReceiver",
		outputs: [{ internalType: "address", name: "", type: "address" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "totalSupply",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "totalWithdrawnForInvestment",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "address", name: "to", type: "address" },
			{ internalType: "uint256", name: "value", type: "uint256" },
		],
		name: "transfer",
		outputs: [{ internalType: "bool", name: "", type: "bool" }],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "address", name: "nextAdmin", type: "address" }],
		name: "transferAdmin",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "address", name: "from", type: "address" },
			{ internalType: "address", name: "to", type: "address" },
			{ internalType: "uint256", name: "value", type: "uint256" },
		],
		name: "transferFrom",
		outputs: [{ internalType: "bool", name: "", type: "bool" }],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "address", name: "from", type: "address" },
			{ internalType: "address", name: "to", type: "address" },
			{ internalType: "uint256", name: "value", type: "uint256" },
			{ internalType: "uint256", name: "validAfter", type: "uint256" },
			{ internalType: "uint256", name: "validBefore", type: "uint256" },
			{ internalType: "bytes32", name: "nonce", type: "bytes32" },
			{ internalType: "uint8", name: "v", type: "uint8" },
			{ internalType: "bytes32", name: "r", type: "bytes32" },
			{ internalType: "bytes32", name: "s", type: "bytes32" },
		],
		name: "transferWithAuthorization",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{ inputs: [], name: "unpause", outputs: [], stateMutability: "nonpayable", type: "function" },
	{
		inputs: [{ internalType: "uint256", name: "amount", type: "uint256" }],
		name: "withdrawReserve",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
];
